# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

설명 생략

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.version)

<module 'numpy.version' from '/Users/choeunsol/opt/anaconda3/lib/python3.9/site-packages/numpy/version.py'>


version을 인수로 넣으면 버전 상태를 확인할 수 있다.

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
x = np.zeros(10)
x.nbytes

80

In [7]:
# 정답
x.itemsize * x.size

80

nbytes라는 옵션이 있는데 왜 memory size를 저렇게 출력했는지는 모르겠음.

memory size는 itemsize와 size의 곱으로 정의된다.

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
import numpy
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

numpy.info를 통해 출력할 수 있다.

R의 ?function과 비슷하게 출력되므로(인수, 예시까지) 인수가 기억이 안나거나 예시를 확인하고 싶으면 이 함수에 익숙해지는 것이 좋다.

스파이더에서 함수를 입력하면 인수 정보가 나오지만, 주피터 노트북에서는 나오지 않기 때문에 궁금하면 info에 정보를 넣어보자.

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


numpy에서는 보다 더 효율적인 인덱싱이 가능하다. 원소의 번호를 slicing해서 원소를 넣어주면 바로 대체된다.

In [14]:
x_test = [0, 0, 0, 0]
x_test[1] = 1
print(x_test)

[0, 1, 0, 0]


이와 같은 작업은 리스트에서도 가능하다.

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

np.arange는 매우 유용하게 쓰이는 함수이다.

np.arange(시작, 끝, step)을 지정하면 np.array를 출력해준다.

다만 리스트를 인덱싱할 때 np.array로 인덱싱하려면 오류가 생기니 참고바람.

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
p8 = np.arange(10, 50)
p8[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [17]:
# 다른 답
np.flip(p8)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

벡터를 뒤집기 위해서는 [::-1]으로 슬라이싱하거나 np.flip() 함수를 이용한다.

flip이 뒤집다라는 의미니 뒤집다라고 생각하자.

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
raw = np.arange(0, 9)
raw.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

간단하게 형성할때부터
    raw.reshape(3,3)이라 해도 된다.

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
index = np.array([1,2,0,0,4,0])
np.where(index != 0)

(array([0, 1, 4]),)

index에서 0이 아닌 것들을 추출한다.

출력은 np.array로 된다.

#### 11. Create a 3x3 identity matrix (★☆☆)

In [54]:
im = np.zeros(9)
im[0] = 1
im[4] = 1
im[8] = 1
im.reshape(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
## 간단한 코드

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

identity matrix를 출력하려면 np.identity(diagonal 개수)로 입력하면 된다.

예를 들어 3 by 3 행렬을 출력하려면 np.identity(3)을 넣어준다.

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [57]:
base = np.random.randn(27)
base.reshape(3,3,3)

array([[[ 1.30380914,  0.61219227, -1.12507059],
        [ 1.07721664,  1.5370292 ,  0.21113375],
        [ 1.13543792, -0.26296114, -1.0314403 ]],

       [[-0.33534962,  1.63050788, -0.47888084],
        [-0.62962907, -1.70138595,  2.09295007],
        [ 0.79090385,  1.33755493, -0.25566221]],

       [[ 0.60637873,  1.05663623,  0.43729919],
        [ 1.1845462 , -1.51689829, -1.41669484],
        [-0.01625318, -0.2410172 ,  1.72692381]]])

In [58]:
np.ndarray((3,3,3))

array([[[1.30380914, 0.61219227, 1.12507059],
        [1.07721664, 1.5370292 , 0.21113375],
        [1.13543792, 0.26296114, 1.0314403 ]],

       [[0.33534962, 1.63050788, 0.47888084],
        [0.62962907, 1.70138595, 2.09295007],
        [0.79090385, 1.33755493, 0.25566221]],

       [[0.60637873, 1.05663623, 0.43729919],
        [1.1845462 , 1.51689829, 1.41669484],
        [0.01625318, 0.2410172 , 1.72692381]]])

np.ndarray에 형상을 넣어주면 자동으로 그 형상에 난수를 채운 행렬을 출력한다.

np.random.randn으로 난수를 출력하는 과정을 생략해도 되니 참고.

In [20]:
np.random.randn(3, 3, 3)

array([[[ 2.24823647, -0.26673355, -0.82234651],
        [-1.09535996,  0.58426851, -1.33746253],
        [ 0.4580547 ,  0.35105984, -0.24694101]],

       [[-1.03880341,  1.10011452, -1.11512893],
        [ 0.09629639,  1.20818206,  0.15420673],
        [ 1.88463947, -0.88694736, -0.81101439]],

       [[-0.72512263, -0.91361351, -0.33854331],
        [-1.29405796, -0.74745494, -2.29668488],
        [ 0.17702088,  0.51941048, -2.37732005]]])

개인적으로 쓰는 방법은 np.random.randn 안에 형상을 넣어주는 것.

난수를 출력하는 목적성이 확실해서 좋다.
    
    np.ones, np.zeros와 마찬가지로 안에 있는 인수들을 명시할 수 있으면 더 직관적으로 가능할 것.

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [42]:
base = np.random.randn(100)
bm = base.reshape(10, 10)
np.max(bm)

2.349566714964909

In [59]:
np.min(bm)

-2.4350448334129706

마찬가지로 np.random.randn( )에 형상을 넣어주면 좋다.

최댓값과 최솟값 출력은 np.max, np.min으로 한다.

In [21]:
## 더 쉬운 코드
base_2 = np.random.randn(10, 10)
np.max(base_2)

3.2707218600023302

In [22]:
np.min(base_2)

-2.2820258940683784

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [44]:
p14 = np.random.randn(30)
np.mean(p14)

-0.11001475889209165

np.random.randn에 대해 설명했으므로 여기서는 설명 생략.

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [87]:
p15 = np.ones_like(p)
p15[1:-1, 1:-1] = 0
print(p15_r)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


두 번째 줄을 인덱싱하는 것이 포인트이다.

np.ones_like는 p와 같은 형상의 array를 출력한다.

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [108]:
p16 = np.random.randn(3,3).reshape(3,3)
np.pad(p16, ((1,1),(1,1)), "constant", constant_values = 0) 

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.48582453, -1.45769382,  0.75662725,  0.        ],
       [ 0.        , -1.46809427,  0.43754746,  0.84258992,  0.        ],
       [ 0.        ,  2.45271646,  1.14875521,  0.54795825,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

padding은 신경망 모델에서 쓰이는 중요한 개념이니 알고 있자.

In [115]:
np.pad(p16, ((2,2), (1,1)), "constant", constant_values = 0)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.48582453, -1.45769382,  0.75662725,  0.        ],
       [ 0.        , -1.46809427,  0.43754746,  0.84258992,  0.        ],
       [ 0.        ,  2.45271646,  1.14875521,  0.54795825,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [23]:
np.info(np.pad)

 pad(array, pad_width, mode='constant', **kwargs)

Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
  

두 번째 인수에 padding할(matrix를 확장할) 범위를 넣어준다.

예를 들어 세로 상 하를 2줄 늘리고 싶으면 두 번째 인수의 첫 번째 항에 (2,2)를 넣어주면 된다.

    특정 인수를 채우고 싶으면 'constant'를 입력하고 constant_values = scalar를 넣어주면 되는데,
    이 인수의 종류에 따라 세 번째 인수가 달라진다.
    
    minimum, median, mean... 등을 넣어줄 수 있으며, 나머지는 위의 info를 참고하자.

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [26]:
0 * np.nan # 파이썬에서는 NA값과 Null 값을 모두 nan으로 처리한다. 없는 값에 0을 곱해봤자 변하지 않으므로 답은 nan.

nan

In [29]:
np.nan == np.nan # 정해지지 않은 값이므로 이 두 값은 동일하지 않다.

False

In [30]:
np.inf > np.nan # nan 값은 크기 비교가 불가능하다.

False

In [32]:
np.nan - np.nan # nan 값은 정해지지 않은 값이라고 이해하는 것이 중요. nan에 어떤 연산을 해도 값은 nan이 나올 것.

nan

In [34]:
np.nan in set([np.nan]) # set는 집합 개념으로 생각하면 편하다. nan 값의 집합에 nan이 속하냐는 질문이므로 True.

True

In [35]:
0.3 == 3 * 0.1 
## 파이썬에서 숫자는 부동소수점으로 표현된다. 즉, 0.3과 0.1을 표현할 때, 0.3과 0.1 자체가 아니라 0.3x를 근사해서 표현한다는 것.
## 2진 분수로 숫자를 표현하기 때문에 정확한 표기값이 다르다. 따라서 False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [92]:
np.diag([1,2,3,4], k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

앞에서의 np.pad로도 표현할 수 있지만, np.diag의 k 옵션을 쓰는 것이 깔끔하다.

    np.diag의 k 값은 diagonal elements들을 올려주거나 내려준다.
    
    예를 들어 위에서 k=1을 입력하면 5 by 5 diagonal에서 한 칸 위로 1, 2, 3, 4를 가지는 값이 만들어질 것이다.

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [48]:
p19 = np.array([[0,1], [1,0]])

np.tile(p19, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

np.tile은 해당되는 array를 다음의 인수의 형상대로 쌓아준다.

    위를 보면 [[0,1], [1,0]]이 반복할 대상이다.
    
    이를 행 방향으로 4번 쌓고, 열 방향으로 4번 쌓는다.
    
    먼저 [0,1]부터 행 방향으로 4번 쌓고, 다음으로 들어가는 [1,0]을 4번 쌓은 다음, 이것을 열 방향으로 4번 반복한다.

In [119]:
# pile이 아닌 다른 방법

c19 = np.zeros((8, 8))
c19[::2, 1::2] = 1 
c19[1::2, ::2] = 1
print(c19)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


'::x'는 x 간격으로 인덱싱한다.

    ::-1일 경우에는 역순이 된다. -1칸 간격으로 데이터를 뽑아내라는 것이기 때문.
    따라서 ::-2는 역순으로 2칸 간격, ::-3은 역순으로 3칸 간격... 이 된다.

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [120]:
array = np.random.randn(6, 7, 8)
hth = array.flatten()[99]
np.where(array == hth)

(array([1]), array([5]), array([3]))

안에 있는 값을 기반으로 위치를 뽑아내려면 np.where을 활용한다.

In [121]:
# 더 쉬운 방법
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [122]:
np.info(np.unravel_index)

 unravel_index()

unravel_index(indices, shape, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``shape``. Before version 1.6.0,
    this function accepted just one index value.
shape : tuple of ints
    The shape of the array to use for unraveling ``indices``.

    .. versionchanged:: 1.16.0
        Renamed from ``dims`` to ``shape``.

order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1]))
>>> np.unrave

    np,unravel_index(index, shape)는 shape의 형상을 한 행렬에서 index번째의 요소의 (x, y, z)를 뽑아준다.

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [49]:
p19 = np.array([[0,1], [1,0]])

np.tile(p19, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

위와 같다.,

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [50]:
mt = np.random.randn(5, 5)

mu = np.mean(mt)
std = np.std(mt)

(mt - mu) / std

array([[-0.23593579,  0.98524195, -1.61415405,  1.7765972 ,  0.79459242],
       [ 1.10153559,  0.35672257,  0.87288854,  0.16858023,  0.83285218],
       [-0.06456011, -1.08288635, -0.87978719, -0.03874594, -1.37421965],
       [-0.76213961,  0.26088159, -1.66332546,  0.43251134, -0.64321746],
       [ 0.30343559, -1.89864864,  1.39574793,  1.11142833, -0.13539522]])

sklearn에서는 옵션이 있지만, 여기서는 평균과 표준편차를 구해 직접 표준화해줘야 한다.

    표준화 방법은 데이터에서 평균을 빼고 표준편차를 나누는 것.

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [263]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

    np.dtype에서 데이터 타입을 설정해줄 수 있다.

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [51]:
mat1 = np.random.randn(5, 3)
mat2 = np.random.randn(3, 2)

np.matmul(mat1, mat2)

array([[-1.67431119,  1.88520663],
       [-1.59412839,  0.81566909],
       [-4.36515659,  2.78707047],
       [-0.24808722, -0.55726556],
       [ 0.65206338, -0.85954914]])

np.dot과 np.matmul 두 옵션이 있다.

    다만 np.dot은 vector 계산에도 적용이 되므로 np.matmul로 행렬 계산을 명시해주는 것이 낫다 생각.
    
앞에서도 말했듯이 나름대로의 코딩 법칙이긴 한데, 되도록이면 뭘했는지 코드에서 직관적으로 알 수 있게 코드를 짜고 있슴다

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [74]:
arr = np.arange(30)

arr[(arr > 3) & (arr < 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

추출할 때 조건에 ()을 씌워주는 것이 포인트이다. 씌워주지 않을 경우에는 계산이 진행되지 않는다.

여기서는 3과 8 사이에 있는 것들을 -를 씌워주어야 하므로 *= -1을 넣어준다.

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [75]:
print(sum(range(5),-1))

9


In [139]:
import numpy as np
print(sum(range(5), -1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [142]:
Z = np.arange(10, dtype = np.int32)

In [144]:
Z**Z # Z의 인수들을 인수들로 제곱시킨다. legal.

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [169]:
2 << Z >> 2 # 비트를 왼쪽 2자리, 오른쪽 2자리로 민다.

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32)

In [173]:
Z <- Z # Z를 할당시키려는 시도? 그런데 Z > -Z을 계산하는 bool로 뜬다. illegal.

array([False, False, False, False, False, False, False, False, False,
       False])

In [176]:
1j*Z # j는 imaginary number i를 의미한다.

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [180]:
Z/1/1 # integer가 아닌 float로 출력된다.

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [183]:
Z<Z>Z # illegal. 변수가 하나 이상 있어야 한다.

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

뭘 의도한 문제인지 모르겠음..?

넘파이가 아니라 메모리 관련해서 파이썬 연산자들을 모아놓은 것 같은데, 질문 자체가 그냥 성립하냐.. 이걸 물어봐서..

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [185]:
np.array(0) / np.array(0) # 0/0은 nan으로 출력.

/var/folders/d7/8zsbg3r51rs_vl832mx18q_00000gn/T/ipykernel_5589/187993282.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0) # 0/0은 nan으로 출력. 계산이 불가능하므로..


nan

In [187]:
np.array(0) // np.array(0) # 0/0의 몫은 nan이 아닌 0으로 출력된다.

/var/folders/d7/8zsbg3r51rs_vl832mx18q_00000gn/T/ipykernel_5589/2246737887.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) # 0/0의 몫은 nan이 아닌 0으로 출력된다.


0

In [190]:
np.array(0) % np.array(0) # 0/0의 나머지도 0으로 출력된다. 계산 자체는 할 수 없지만, 몫과 나머지는 0으로 구할 수 있다.

/var/folders/d7/8zsbg3r51rs_vl832mx18q_00000gn/T/ipykernel_5589/3456432912.py:1: RuntimeWarning: divide by zero encountered in remainder
  np.array(0) % np.array(0) # 0/0의 나머지도 0으로 출력된다. 계산 자체는 할 수 없지만, 몫과 나머지는 0으로 구할 수 있다.


0

In [191]:
np.array([np.nan]).astype(int)

array([-9223372036854775808])

In [192]:
np.array([np.nan]).astype(int).astype(float) # np.nan은 not a number이지만, int와 float로 표현할 수 있다.
## 터무니 없이 작은 값이 나온다.

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [247]:
flt = np.arange(10).astype(np.float)

print(np.where(flt>0, np.ceil(flt), np.floor(flt)))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


/var/folders/d7/8zsbg3r51rs_vl832mx18q_00000gn/T/ipykernel_5589/3384844810.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  flt = np.arange(10).astype(np.float)


In [251]:
np.info(np.where)

 where()

where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples
--

#### 30. How to find common values between two arrays? (★☆☆)

In [227]:
a = np.arange(10).reshape(2, -1)
b = np.arange(5, 21)[::-1].reshape(2, -1)

np.intersect1d(a, b)

array([5, 6, 7, 8, 9])

intersect1d는 교집합의 개념으로 생각하자.

따라서 순서가 달라도 그 안에 있는 같은 값이 있으면 출력한다.

1d라는 것은 출력값을 의미하는 것, 위처럼 다차원 array일 경우에도 공통값을 뽑아준다.

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [261]:
with np.errstate(all='ignore'):
    np.array(2) // 0

In [262]:
np.array(2) // 0 

/var/folders/d7/8zsbg3r51rs_vl832mx18q_00000gn/T/ipykernel_5589/1863088232.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(2) // 0


0

    np.errstate(all = 'ignore')은 warning 창을 띄어주는 것을 막아준다.
    
주의할 점은 '오류창'을 지워주는 것이 아니다. 에러 창이 나타나는 것은 저 코드를 입력해도 에러 창이 나타난다.

warning은 계산은 되는데, 이상하게 계산되는 것에 나타나는 것(예를 들어 0으로 나누는 것).

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [213]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/d7/8zsbg3r51rs_vl832mx18q_00000gn/T/ipykernel_5589/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [215]:
np.sqrt(-1) # np.sqrt에서 negative value를 넣으면 출력되지 않는다.

/var/folders/d7/8zsbg3r51rs_vl832mx18q_00000gn/T/ipykernel_5589/357378591.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) # np.sqrt에서 negative value를 넣으면 출력되지 않는다.


nan

In [217]:
np.emath.sqrt(-1) # np.emath.sqrt는 negative value를 넣으면 허수값이 출력된다.

1j

numpy의 공식 설명에도

    np.sqrt와 np.emath.sqrt는 양수 범위에서는 똑같은 값을 출력하지만, 음수 값을 넣을 때 np.emath.sqrt를 활용해야 한다

라고 적혀있다.

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [229]:
np.datetime64('today')

numpy.datetime64('2023-01-12')

In [231]:
np.datetime64('today') + timedelta64(1)

numpy.datetime64('2023-01-13')

In [233]:
np.datetime64('today') - timedelta64(1)

numpy.datetime64('2023-01-11')

    np.datetime64('today')를 이용해 오늘 날짜를 뽑아낼 수 있다.
    
    주의해야 할 점은 timedelta64를 통해 날짜 계산을 해야 한다는 것. 날짜는 dtype이 np.datetime64이다. integer이나 float처럼 생각하면 안된다.
    
    numpy 말고도 datetime을 불러와서도 수행할 수 있다.

In [238]:
from datetime import *

datetime.today()

datetime.datetime(2023, 1, 12, 22, 26, 28, 926305)

In [239]:
datetime.today() + timedelta(1)

datetime.datetime(2023, 1, 13, 22, 26, 41, 790883)

In [242]:
datetime.today() - timedelta(1)

datetime.datetime(2023, 1, 11, 22, 27, 7, 665539)

넘파이가 출력하는 yyyy-mm-dd 형식이 싫을 때는 datetime에서 숫자를 가져와서 재조직해보자.

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [80]:
bs = np.random.randn(16, 16)
window = np.arange(4, 20, 4)
block_list = []

for idx in range(4):
    block = bs[idx * 4, idx * 4]
    block_sum = np.sum(block)
    block_list.append(block_sum)

np.array(block_list)

array([ 1.7571568 ,  0.52851733, -3.59086913,  1.92370948])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
def n_largest_values(array, n = 5):
    for i in range(n):
        if i !== n:
            idx = np.max(array)
            array = np.where(array != idx)
            

In [106]:
array = np.arange(10)
tw = np.where(array != 5)
ton = np.where(tw != 1)
tw

(array([0, 1, 2, 3, 4, 6, 7, 8, 9]),)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)